### ISSUE TITLE
/help modules

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#12]
Funktioniert nicht
"modules
Dieser Befehl existiert nicht oder es gibt keine Hilfestellung. Gib /help help an, um mehr über diesen Befehl zu erfahren."

**Comment by MoorhuhnHD** [comment]
Im Moment sind noch nicht für alle Einträge Hilfstexte vorhanden.

**Comment by DxnnySch** [comment]
Duplicate if #11
