### ISSUE TITLE
#tolkienfeed

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#13]
Dass die Sub2XY getaggt werden anstatt niemand

**Comment by ghost** [comment]
Man kanns ja mal probieren -> Wenn das letztendlich nicht gut ist kann man es ja wieder rückgängig machen

**Comment by DxnnySch** [comment]
Ist umgesetzt, Testing läuft.

**Comment by DxnnySch** [comment]
Funktioniert.
