### ISSUE TITLE
Neues Levelsystem?

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#18]
Eriol Vorschlag: 
Druadan unter Adan schieben und alles eine Ebene hochdrücken?
Und Hobbits und Zwerge auch wo reinschieben?
Weil dann muss man echt viel Leveln um zu Maia zu kommen
Mit dann gesamt 8 Rängen hätten wir:
Druadan:            0-49
Hobbit:                50-149
Adan:                   150-299
Dunadan:            300-499
Peredhel:            500-749
Moriquende:      750-1049
Calaquende:      1050-1399
Maia:                    1400+

**Comment by DxnnySch** [comment]
Done.
