### ISSUE TITLE
Reaktionen im Modlog

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#22]
Dass im Modlog auf Reports Reaktionen gesendet werden:
Ist nichts - Kick - Bann - Strafen im Adminchat diskussieren

Dass beim letzten der Report zitiert wird und der Bilbot eine Nachricht mit @Vala in den Adminchat schickt

Die Frage ist inwiefern die Kicks - Banns sinnvoll sind 

Kick wäre eigentlich erst bei Mods sinnvoll.
Bann eigentlich gar nicht (weil eh erst Absprache und dann per Befehl mit Angabe von Grund)

**Comment by DxnnySch** [comment]
Ich würde Kick und Bann einführen und als Grund den jeweiligen Report-Text nehmen. 
Weitere Option: Exil (kann gleich von jedem genutzt werden)
Für Kick und Ban werden evtl. einfach mehrere Votes (2 oder 3) benötigt.
