### ISSUE TITLE
#modlog log für XP - Coins Vergabe

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#23]
Nachricht im Modlog, wenn XP oder Coins per Befehl vergeben werden
Mit Inhalt. 
Welcher Nutzer bekommt - wieviel Coins - von wem

**Comment by DxnnySch** [comment]
Ausgehend vom /coins give bzw. /xp give oder coins gift Befehl?

**Comment by ghost** [comment]
vom /give Befehl
Beim gift Befehl ist ja eine Ausgabe vorhanden, die im Cat stehen bleibt. 
Das würde ich beim give Befehl nicht machen sondern gleich die Nachricht im Modlog
