### ISSUE TITLE
Böse Wörter Liste  anpassen

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#24]
Parteien rausnehmen, mehr Beleidigungen wie A*schlch, Beh*ndert etc. einfügen

**Comment by DxnnySch** [comment]
Wenn du mir eine Liste o.Ä. gibst, kann ich das ändern.

**Comment by ghost** [comment]
Kannst du mir mal die bisherige Liste schicken?

**Comment by DxnnySch** [comment]
"pisser", "hure", "fick", "fotze", "brezelsalzabpopler", "inzest", "bastard", "spast", "wichser", "wixxer", "\u5350", "afd", "cdu", "csu", "spd", "npd", "nsdap", "hitler", "hodenkobold"

"\u5350" ist ein Hakenkreuz.

**Comment by ghost** [comment]
Meine verbesserte Böse Wörter Liste einfügen
