### ISSUE TITLE
Musikbot Nachricht

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#25]
**Is your feature request related to a problem? Please describe.**
Beim Musikbot sieht man nicht, wer das neuste Lied eingestellt hat

**Describe the solution you'd like**
Es wird angezeigt wer das Lied zur queue hinzugefügt hat

**Additional context**
In der Nachricht: Adding to queue das Lied (wie bisher) + angefordert von NUTZERNAME

**Comment by DxnnySch** [comment]
Hinzugefügt.
