### ISSUE TITLE
Formeln Levelberechnung

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#26]
irgendwo für alle einsehbar machen. 
Ob durch einen Befehl (/xp formel)
in /help xp, oder in die allgemeinen Infos

**Comment by DxnnySch** [comment]
Warum ist das notwendig? Ab LVL 50 erfährt man doch alles Notwendige über /xp next, oder?

**Comment by ghost** [comment]
Ja, trotzdem wäre es zumindest für Admins ganz interessant
