### ISSUE TITLE
im #exil keine XP mehr bekommen.

### ISSUE THREAD

**Issue by Melbarion** [MoorhuhnHD/BilboT#30]

**Comment by MoorhuhnHD** [comment]
Bitte Label benutzen ;)
Ansonsten kann man den #exil in #exil-spam umbenennen, bis es eine bessere Lösung gibt.

**Comment by MoorhuhnHD** [comment]
In dem man in die Beschreibung ein {SPAM} schreibt, kann man die XP-Vergabe verhindern.
