### ISSUE TITLE
/music join VOICECHANNEL

### ISSUE THREAD

**Issue by Melbarion** [MoorhuhnHD/BilboT#34]
UND! /music join VOICECHANNEL ist eine gute Idee, aber aufgrund des Emojis im Namen des Channels schwierig. Man muss auf Einstellungen des Channels gehen und kann da den Namen copypasten. Für normale Nutzer nicht nutzbar.

**Comment by MoorhuhnHD** [comment]
Wenn man in einem Voicechannel ist, und /music join eingibt, dann joint der Bot automatisch.
