### ISSUE TITLE
Die SingingDwarves werden nicht aktiviert.

### ISSUE THREAD

**Issue by DxnnySch** [MoorhuhnHD/BilboT#34]
**Describe the bug**
Verschiedene Musikanfragen aus unterschiedlichen Channeln → Der BilboT switcht hin und her.

**Expected behavior**
Bei einem zweiten, dritten oder vierten Anforderungsversuch aus anderen Channeln sollten die Singing-Dwarves übernehmen.

Seit v2.8.0

**Comment by ghost** [comment]
closed?
