### ISSUE TITLE
/music pause

### ISSUE THREAD

**Issue by Melbarion** [MoorhuhnHD/BilboT#35]
Nach /music pause kann man den Bot nicht mehr mit /music play XY ein neues Lied abspielen lassen. Der einzige Weg momentan den Bot wieder zum Laufen zu bringen ist /music reset (und evtl /music stop, hab ich nicht getestet).

**Comment by MoorhuhnHD** [comment]
Theoretisch müssten die Befehle /music resume bzw. /music pause diesen Effekt beheben.
