### ISSUE TITLE
/music volume Berechtigung

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#36]
Nur für Vala oder nur ab einem bestimmten Rang. Bietet viel Troll-Potential.

**Comment by DxnnySch** [comment]
Ab welchem Rang würde das denn Sinn machen?

**Comment by ghost** [comment]
Ist ja letztendlich die Lautstärke Regelung im Rechtsklick Menü, nur dass es alle betrifft. Deswegen sollte man den Befehl nur für diejenigen Freischalten, denen man vertraut. 

Je höher die Aktivität, desto stärker das Vertrauen? 
-Meine Antwort: Nein. Nur für Admins. Für Leser würde es auch etwas Sinn machen.
