### ISSUE TITLE
/event

### ISSUE THREAD

**Issue by Melbarion** [MoorhuhnHD/BilboT#4]
/event lyrikecke start 
	/event lyrikecke stop 
	/event lyrikecke setup 
	/event lyrikecke storyteller set NUTZER 
	/event lyrikecke storyteller get 
	/event lyrikecke storyteller clear 
	/event lyrikecke diskussion everyone 
	/event lyrikecke diskussion experte

Diese alten Befehle funktionieren nicht (oder ich mach was falsch)
Und die neuen kann ich nicht aus dem Quellcode auslesen

**Comment by MoorhuhnHD** [comment]
Statt "lyrikecke" "narration" benutzen.
