### ISSUE TITLE
Beim Verlassen des laufenden Lyrikabends wird die Stummschaltung nicht aufgehoben

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#43]
Lösung könnte evtl so gehen:

Wenn der Lyrikecke-Voicerang entfernt wird: mute immer mit entfernen (halt beim Verlassen)

aber wenn jemand von uns den mute Rang bekommt, könnte der ihn so wegbekommen

Also: Wenn der Eventwert (1 oder 0) auf 1 ist und der Voicerang entfernt wird -> Mute entfernen

ABER das ist mit Fehlern behaftet, weil der Voicerang nicht immer weggenommen wird. Jetzt gerade hatten 2 Leute den Rang noch. 
Das spricht für eine Entkoppelung der beiden Ränge. Die auch abseits des Problems mehr Sinn für das Ökosystem Bilbot machen würde.

**Comment by DxnnySch** [comment]
Mutes laufen im Moment unabhängig vom mute-Rang. Das Problem ist, dass ein Nutzer nur ge- bzw. entmuted werden kann, wenn er sich in einem Voicechannel befindet, was beim Verlassen nicht der Fall ist.
Es müsste also ein Entmuten beim Joinen stattfinden, was im Moment auch so umgesetzt wird, bis eine bessere Lösung umgesetzt wird.
