### ISSUE TITLE
Rang über Maia

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#46]
Es gibt durch das neuste Pfingstupdate zwar mehr Ränge, allerdings werden diese auch in 1-2 Jahren ausgeschöpft sein. 

Ein neuer Rang über Maia wäre super, damit würde man das Erreichen der höchsten Ränge etwas schwieriger machen. 

Da es über Maia aber eigentlich nichts gibt, könnte man einen Kirinki Rang einführen. Um den +50Lvl Schritten zu folgen, müsste der Rang Maia 350 Level umfassen (also statt 1050-∞ dann 1050-1399).
Der Kirinki Rang wäre dann ab Level 1400 bis Level ∞

Zudem hätte der Kirinki-Rang auch die Nutzerseitige Akzeptanz um über Maia zu stehen.

**Comment by DxnnySch** [comment]
Die Rangreihenfolge und -anzahl ist im Moment komplett genügend. :)
