### ISSUE TITLE
/role 

### ISSUE THREAD

**Issue by Melbarion** [MoorhuhnHD/BilboT#5]
/role create funktioniert bei mir nicht

**Comment by MoorhuhnHD** [comment]
Was genau geht nicht?

**Comment by Melbarion** [comment]
Naja /role create ABC sollte doch die Rolle ABC machen. Oder verstehe ich den Befehl falsch?

**Comment by MoorhuhnHD** [comment]
Nein, die Wortwahl ist vermutlich irreführend. Mit `/role create` wird eine Rolle durch den `/role add`-Befehl aufrufbar. Selbiges gilt für `/role delete` bzw. `/role remove`.
