### ISSUE TITLE
Entkopplung der einzelnen Features

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#50]
Das wäre ein langes zäher Prozess. Aber die Arbeit sollte sich auszahlen. 

Ich weiß nicht genau wie eng die einzelnen Features vom Bilbot miteinander verknüpft sind. Aber ich glaube es würde deutlich helfen, wenn man sie einzeln vollkommen entkoppelt und die einzige Schnittstelle der Features eine Datenbank wäre.

**Comment by DxnnySch** [comment]
Ich weiß gerade nicht genau was du meinst, kannst du mir ein Beispiel bringen?
