### ISSUE TITLE
Troll Report - Benachrichtigung über Menge der abgezogenen Coins

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#59]
In die "Report wurde bearbeitet" Nachricht die Menge der abgezogenen Coins mit reinschreiben. 

Evtl das auch noch in die Nutzer-Nachricht mit reinschreiben. Aber da wäre ich vorsichtig.

**Comment by DxnnySch** [comment]
In der Nutzernachricht stehen eh die 5% drin. Die müssen auch nicht mehr wissen ^^
