### ISSUE TITLE
Quiz-Annahme, verbesserte Übersicht in #Expertengremium

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#69]
Fertig bearbeitete Quiz's im #expertengremium löschen. Um so die Übersicht zu behalten, welche noch zu Bearbeiten sind

**Comment by DxnnySch** [comment]
Da es wichtig sein kann zu wissen, wie mit welcher Frage verfahren wurde (und warum), werde ich davon absehen die Nachrichten zu löschen.

**Comment by ghost** [comment]
Eventuell eine neue Nachricht schreiben lassen, die sehr minimal gehalten wird. 
Theoretisch könnte man das ja auch in die "Frage von NUTZER wurde zugelassen"-nachricht soweit editieren, dass statt der "Frage" Verlinkung folgendes steht: 

Frage von Moorhuhn wurde zugelassen:
Warum ist die banane krumm? [Weil Baum; Erde steht immer in der Luft; Australien steht Kopf]
Zuständige Experten: NUTZER1, NUTZER2

**Comment by DxnnySch** [comment]
Macht mMn keinen wirklichen Unterschied. Zudem wird es im Kontext evtl unübersichtlich, weil Diskussionen zu einer Frage dann keine ersichtliche Grundlage mehr haben.

**Comment by ghost** [comment]
Heut abend erkläre ich es dir im Voice

**Comment by ghost** [comment]
KLeiner Kommentar für mich: 
Diskussion abgesschlossen, minimalisierte Form der Frage soll Funktion von 1.  Fragen Zulassen übernehmen
