### ISSUE TITLE
/server optimalsettings

### ISSUE THREAD

**Issue by Melbarion** [MoorhuhnHD/BilboT#7]
dieser Befehl macht gar nichts. Nichtmal eine Ausgabe

**Comment by MoorhuhnHD** [comment]
Anders herum. Dieser Befehl macht sehr viel, außer einer Ausgabe. Diese ist in der neusten Version (ab v1.2.11) dann auch enthalten. Trotzdem werden bei dem Befehl die Präferenzen zu einem späteren Zeitpunkt noch überarbeitet.
