### ISSUE TITLE
Quiz-editieren, 2 Stimmen zur Ababe nötig

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#70]
**Is your feature request related to a problem? Please describe.**
Von Experten editierte Quiz's können durch selbigen zugelassen werden. 

**Describe the solution you'd like**
Man braucht 2 Experten um editierte Quiz's zuzulassen, um so stets einen kritischen zweiten Blick zu haben. 

**Problems**
Erhöht den Traffic in #expertengremium

**Comment by DxnnySch** [comment]
Man braucht weiterhin für alle Aktionen, außer das Editieren, 2 Experten. Nach dem Editieren muss die Frage erst wieder zugelassen werden.
