### ISSUE TITLE
Quiz-Editieren, mögliche Bugs

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#71]
Kann leider die Funktion nicht testen und Test-Server ist ja anscheinend stillgelegt. 

--- 1.
Wenn man editiert und sagen wir die Frage hat eine Aantwort und man klickt auf: 10. Antwort editieren. 

Was passiert dann? Wird dann eine 10. Antwort editiert? Oder "rutscht" die editierte Antwort an Stelle 1? 
---
--- 2. 
Man ändert die Anzal der benötigten Antworten von sagen wir 2 auf 4. 
Und lässt Antwort 1 und 2 bestehen und fügt zwei neue Antworten hinzu, aber man macht dies als Antwort 9 und 10. 

Was macht der Bilbot? rutschen neuen Antworten nach unten? Oder wird die Lücke aufgefüllt? 
---

**Comment by DxnnySch** [comment]
Wird alles getestet, sobald ich fertig bin. ;)
