### ISSUE TITLE
Report Beschreibung angeben

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#76]
Bei einem Report kommt irgendwann die Frage: "Gibt es noch weitere Details oder Beschreibungen, die du angeben möchtest? Je besser die Admins über die Situation in Kenntnis gesetzt werden, desto genauer und fairer werden mögliche Konsequenzen ausfallen!"

Wenn man keine Beschreibung schreiben will, muss man trotzdem eine angeben. Ist bissl blöd. Sonst sollte man die Frage ändern.

**Comment by DxnnySch** [comment]
Kommt noch.

**Comment by DxnnySch** [comment]
Obwohl, man kann einfach "Nein" angeben und das Ding ist gegessen...
