### ISSUE TITLE
Verlinkung zur Original Einsendung bei Editierten Quiz-Fragen

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#79]
Ja Titel sagt alles... 
Sonst ist es sehr schwer zu sehen, was geändert wurde.

**Comment by DxnnySch** [comment]
Ist nicht wirklich umsetzbar im Moment und mMn auch nicht unbedingt sinnvoll. Man soll ja einfach die Frage an sich bewerten. Wie sie verändert wurde, macht keinen Unterschied.

**Comment by ghost** [comment]
Könnte man nicht einfach den Link aus der Nachricht: Die Frage von Nutzer wird von Experte editiert
in die fertig editierte stecken? strg c + v quasi

**Comment by DxnnySch** [comment]
Nein, geht leider nicht. Ist aber mit den Fixes gleich auch nicht mehr so relevant.
