### ISSUE TITLE
Frage-Ersteller sollen ihre editierte Nachricht bekommen

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#80]
Damit sie sehen, was sie falsch gemacht haben und dann bessere Fragen erstellen

**Comment by DxnnySch** [comment]
+ einen Grund vom Experten.

**Comment by ghost** [comment]
zusätzlich noch: 

Also einen Grund
und die verbesserte Frage + Antwort

**Comment by DxnnySch** [comment]
genau
