### ISSUE TITLE
Bei falscher Antwort die richtigen anzeigen

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#89]
Titel sagt alles.

**Comment by ghost** [comment]
WICHTIG!!!!!

Die richige/n Antwort/en nur für eine begrenzte Zeit einblenden. Sonst kann man bei schwierigen Fragen einfach im Chat mit dem Bilbot nach der Lösung suchen. Die Anzeigezeit würde ich auch von der Char-Menge der Antwort abhängig machen. Könnte ja die Selbe sein, wie die Zeit zum Antworten.

**Comment by DxnnySch** [comment]
Kürzer.
Aber ja.
Bei mehreren Möglichkeiten aber nur eine (random?)
