### ISSUE TITLE
Streak-Rekord als Nachricht in #chat1

### ISSUE THREAD

**Issue by ghost** [MoorhuhnHD/BilboT#92]
Immer wenn jemand eine Quizfrage falsch hat - Streaknummer mit bisheriger Streak max vergleichen, 
wenn Streakneu > Streak max
Streak max = streakneu

wenn Streakneu < Streak max 
nichts verändern

Und wenn Streakneu > Streak max
Dann Bot-Ausgabe in chat1: Nutzer @NUTZER hat mit XX richtig beantworteten Fragen einen neuen Rekord im Spielmodus Casual des Quizs aufgestellt.

**Comment by DxnnySch** [comment]
Ich würde hier aber unter Umständen eine Mindestanzahl einführen, damit nicht komplett reingespammt wird, wenn alle am Anfang Quiz spielen
